# Site settings
title: "Alexandre Quach - Collective Intelligence Architect"
description: "Executive Preparation coach | Engineering Corporate Collectives | Komyu Founder"
url: "https://quach.fr"
baseurl: ""
repository: "AlexandreQuach/alexandre-quach-public"
layouts_dir: _layout
includes_dir: _includes
theme: null

# Author - Section enrichie pour JSON-LD
author:
  name: "Alexandre Quach"
  title: "Collective Intelligence Architect"
  email: "alexandre@quach.fr"
  bio: "Founder of Komyu, specializing in augmented collective intelligence and engineering corporate collectives."
  
  # Education - Diplômes (Alumni status)
  alumni_of:
    - institution: "ENSTA ParisTech"
      degree: "Ingénieur Systèmes d'Information et de Production"
      year: "2009"
      status: "Alumni"
    - institution: "Sorbonne Paris I"
      degree: "Master II Conseil, Organisation, Stratégie d'entreprise et Systèmes d'Information"
      year: "2009"
      status: "Alumni"
    - institution: "MIT Sloan School of Management"
      program: "Advanced Certificate Executive (ACE)"
      status: "Executive Alumni"
  
  # Certifications professionnelles
  professional_certifications:
    - institution: "Stanford Online"
      program: "Professional Program in Generative AI"
      year: "2025"
    - institution: "Harvard Online"
      program: "Leadership and Communication Programs"
      year: "2024"
    - institution: "UC Berkeley"
      program: "Foundations of Happiness at Work"
      year: "2025"
    - institution: "Daniel Goleman Institute"
      program: "Emotional Intelligence Foundational Skills"
      year: "2025"
  
  # Domaines d'expertise pour JSON-LD
  expertise_areas:
    - "Collective Intelligence"
    - "Human-AI Collaboration"
    - "Organizational Transformation"
    - "ECC Method"
    - "Engineering Corporate Collectives"
    - "Compound Thinking"
    - "Knowledge Graphs"
    - "Hypergraph Learning"
    - "Systems Thinking"
    - "Executive Coaching"
    - "Agile Methodology"
    - "Change Management"
    - "Solution Gatling"
    - "Cogeneration"
    - "Coprompting"
    - "Supermind Architecture"
    - "Silo Elimination"
    - "Cross-functional Leadership"
    - "Transversal Program Management"
  
  # Méthodologies développées
  methodologies:
    - "ECC Method"
    - "Engineering Corporate Collectives"
    - "Compound Thinking Framework"
    - "Knowledge Graph Learning"
    - "Hypergraph Thinking"
    - "Confidence Level Variations Method"
    - "Solution Gatling"
    - "Cogeneration"
    - "Coprompting"
    - "Cincinnatus Network"
    - "Supermind-us Framework"
  
  # Expérience professionnelle
  experience_years: "15+"
  certifications_count: "20+"
  
  companies_worked:
    - "Thales"
    - "BNP Paribas"
    - "GRDF"
    - "France Télévisions"
    - "Amadeus"
  
  # Profils sociaux
  social_profiles:
    - "https://www.linkedin.com/in/alexandrequach"
    - "https://www.komyu.fr"
    - "https://github.com/alexandrequach"
    - "https://quach.fr"
  
  # Informations géographiques
  location:
    city: "Paris"
    region: "Île-de-France"
    country: "France"
    country_code: "FR"

# Informations sur l'entreprise
company:
  name: "Komyu"
  url: "https://www.komyu.fr"
  description: "Next-generation collective intelligence consulting firm"
  founding_year: "2022"
  industry: "Management Consulting"
  specialties:
    - "Collective Intelligence"
    - "Organizational Transformation"
    - "Human-AI Collaboration"
    - "Executive Coaching"
    - "Silo Elimination"
    - "Cross-functional Leadership Development"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# Collections for your content structure
collections:
  profile:
    output: true
    permalink: /profile/:name/
  frameworks:
    output: true
    permalink: /frameworks/:name/
  insights:
    output: true
    permalink: /insights/:name/

# Defaults for collections
defaults:
  - scope:
      path: ""
      type: "profile"
    values:
      layout: "page"
      category: "profile"
  - scope:
      path: ""
      type: "frameworks"
    values:
      layout: "page"
      category: "frameworks"
  - scope:
      path: ""
      type: "insights"
    values:
      layout: "page"
      category: "insights"

# SEO and AI optimization
seo:
  name: "Alexandre Quach"
  type: "Person"
  links:
    - "https://github.com/alexandrequach"
    - "https://linkedin.com/in/alexandrequach"
    - "https://www.komyu.fr"

# Schema.org structured data
schema:
  person:
    "@type": "Person"
    name: "Alexandre Quach"
    jobTitle: "Collective Intelligence Architect"
    worksFor: "Komyu"
    address:
      locality: "Paris"
      country: "France"
    nationality: "French"
    gender: "Male"
    birthPlace: "France"
    
  organization:
    "@type": "Organization"
    name: "Komyu"
    url: "https://www.komyu.fr"
    foundingDate: "2022"
    industry: "Management Consulting"
    address:
      locality: "Paris"
      country: "France"

# Navigation
navigation:
  - title: "Profile"
    url: /profile/
  - title: "Frameworks"
    url: /frameworks/
  - title: "Insights"
    url: /insights/

# Professional data for rich snippets
professional:
  role: "Collective Intelligence Architect"
  company: "Komyu"
  industry: ["Management Consulting", "Organizational Development", "Executive Coaching", "Collective Intelligence", "AI Collaboration"]
  target_clients: ["Transversal Leaders", "Program Managers", "Transformation Leaders", "Cross-functional Teams", "Executive Teams"]
  value_proposition: "Engineering Corporate Collectives that amplify quality and speed of both group decision-making and collective execution through systematic approaches and proven methodologies"
  
  unique_selling_points:
    - "15+ years large enterprise experience"
    - "Engineering mindset applied to human systems"
    - "Proven ECC Method"
    - "Elite education portfolio (MIT Sloan, ENSTA, Sorbonne)"
    - "East-West philosophical integration"
    - "Martial arts discipline (15+ years)"
    - "Continuous learning commitment"
    - "Human-AI collaboration pioneer"
    - "Silo elimination expert"

# Language and localization
language: "en"
locale: "en_US"
timezone: "Europe/Paris"

# Contact information
contact:
  email: "alexandre.quach@komyu.fr"
  phone: null  # Pas publié
  address:
    locality: "Paris"
    region: "Île-de-France"
    country: "France"
    postal_code: null  # Pas publié

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

# Include
include:
  - _pages
  - _includes

# Sass
sass:
  style: compressed

# Performance optimization
future: false
incremental: true
profile: false


# Ajoutez ces sections pour l'auto-génération
content_auto_detection:
  frameworks:
    - "ECC Method"
    - "Compound Thinking" 
    - "Solution Gatling"
    - "Supermind-us"
    - "Cincinnatus Network"
  
  expertise_keywords:
    - "collective intelligence"
    - "organizational transformation"
    - "executive coaching"
    - "human-AI collaboration"
  
  company_keywords:
    - "alexandre quach"
    - "komyu"
    - "collective intelligence architect"
